### ISSUE TITLE
Enable dark mode

### ISSUE THREAD

**Issue by HonzaR** [Electric-Coin-Company/zashi-android#1011]
## Is your feature request related to a problem? Please describe.
Once we decide to support dark app mode, we need to check and possibly enhance the UI of all the apps's screens and enable it with the Gradle `IS_DARK_MODE_ENABLED` option.  

## Describe the solution you'd like
- Electric-Coin-Company/zashi#32
- `gradle.properties#IS_DARK_MODE_ENABLED = true`

**Comment by true-jared** [comment]
Final designs in Figma: https://www.figma.com/file/vYQD6uZtkPgtmgJ3zfauq0/Zashi-UI?type=design&node-id=4927-32372&mode=design
