### ISSUE TITLE
Addresses can be shown with "×" symbols

### ISSUE THREAD

**Issue by daira** [Electric-Coin-Company/zashi-android#1032]
### Describe the issue
The u-address display on the Receive screen (both below the QR code and on the "See address details" screen) shows `×` (U+00D7 MULTIPLICATION SIGN) for some addresses. `×` is not a valid character in Base32m. These appear to only occur between decimal digits, so a plausible explanation is that the display API is replacing `<digit>x<digit>` with `<digit>×<digit>`.

I cannot see whether this also happens for Sapling and t-addresses because the ones for my wallet coincidentally do not contain that pattern (it's less likely because the addresses are shorter).

### Can you reliably reproduce the issue?
Yes, the above pattern in an address appears to be common enough to easily reproduce the issue for many random addresses.

### Expected behavior
All characters should be displayed using the usual Base32m alphabet. The API used to display them should have no "clever" behaviour that replaces any characters whatsoever.

- App Version: 0.2.0 (241)
- Android Version: 13 (build V14.0.10.0.TGOEUXM)
- Device: [Xiaomi Redmi A2 (23028RN4DG)](https://www.gsmarena.com/xiaomi_redmi_a2-12124.php)

### Screenshots
![Screenshot_20231108-214649](https://github.com/zcash/secant-android-wallet/assets/643204/a4bd46dc-709e-4c92-8ec7-7d4e8d9d000d)
![Screenshot_20231108-214746](https://github.com/zcash/secant-android-wallet/assets/643204/5b236e42-4693-46cf-8d23-7ba90e703371)

**Comment by daira** [comment]
This is a ligature replacement enabled by default in the Inter font: https://github.com/rsms/inter/issues/222

**Comment by HonzaR** [comment]
I just analyzed this problem.  Currently, there is no reliable way to disable ligatures in Jetpack Compose, which we use on Android, and it seems similar for the iOS side. We'll introduce a new, ideally monospace font for such a case. We can switch to the app's secondary font, Archivo, which does not suffer from this issue until then.

**Comment by HonzaR** [comment]
From Richard:
_looks like Roboto Mono may be a good substitute? https://fonts.google.com/specimen/Roboto+Mono?preview.text=x400abkdg45_

**Comment by daira** [comment]
Was this fixed by #1213?

**Comment by HonzaR** [comment]
Yes, this is now fixed by using the secondary existing font (Archivo) in the app. We've agreed that using a Mono space font is the option for such use cases. Filed a follow-up for that #1248.
