### ISSUE TITLE
Add Paste from buffer to Restore screen

### ISSUE THREAD

**Issue by HonzaR** [Electric-Coin-Company/zashi-android#1060]
## Is your feature request related to a problem? Please describe.
Analyze and consider adding the `Paste from buffer` feature to the Restore Seed screen in the form of a tertiary button

## Describe the solution you'd like
The logic could be something like this:
```
val clipboardManager = context.getSystemService(Context.CLIPBOARD_SERVICE) as ClipboardManager
val clip = clipboardManager.primaryClip
if (clip != null && clip.itemCount > 0) {
    val item = clip.getItemAt(0)
    val text = item.text
}
```

**Comment by true-jared** [comment]
Closing for security concerns.
