### ISSUE TITLE
Ensure that Zashi Android follows the intended key and database backup behaviour for 1.0

### ISSUE THREAD

**Issue by str4d** [Electric-Coin-Company/zashi-android#1231]
Make sure that Zashi Android is doing the same thing wrt key management and storage as Zashi iOS for 1.0, as much as is feasible.

**Comment by HonzaR** [comment]
@str4d could you please provide more details for this task. Thank you.

**Comment by nuttycom** [comment]
@true-jared if this issue should not be part of 1.0, the title should be changed to more accurately reflect the task.

**Comment by true-jared** [comment]
I looked into this, and this conclusion has been reached [here](https://app.zenhub.com/workspaces/wallet-5db8aa0244512d0001e0968e/issues/gh/electric-coin-company/zashi/20):

> For iOS version 1.0, we will continue to back up the database, and the wallet startup flow will prompt the user to provide a seed phrase. We will ensure:
> This seed phrase is validated wherever it is used in the wallet migrations.
> The SDK provides a mechanism to validate the seed phrase to handle the case where no migrations run.
> For Android version 1.0, transferring between devices will require a full restore from seed.

I believe we can actually close this. What do you think? @nuttycom

**Comment by nuttycom** [comment]
@true-jared that seems fine; we should create a separate issue to track what we want to do to bring Android to parity.;
