### ISSUE TITLE
Create screen for selecting the lightwalletd server

### ISSUE THREAD

**Issue by str4d** [Electric-Coin-Company/zashi-android#1235]
This will be reachable from the advanced settings screen (#1234).

**Comment by true-jared** [comment]
This is the design we have in Figma atm: https://www.figma.com/file/vYQD6uZtkPgtmgJ3zfauq0/Zashi-UI?type=design&node-id=3512-18147&mode=design&t=tMaLogYWxx3VAjBi-4

**Comment by HonzaR** [comment]
Possible values for testing: https://status.zcash-infra.com/
