### ISSUE TITLE
Provide link to licensing text in Zashi-Android app description for Google Play Store

### ISSUE THREAD

**Issue by daira** [Electric-Coin-Company/zashi-android#1240]
Do whatever is needed to specify to users that the text written for https://github.com/Electric-Coin-Company/zashi/issues/23 applies.

According to https://android.stackexchange.com/questions/230478/where-is-the-license-information-for-an-android-app-displayed there is no specific way for a user to see what license a Google Play app is distributed under (weak confidence). I guess it could be in the app description. Searching for an official way to specify license text only turned up hits about the [licensing service](https://developer.android.com/google/play/licensing) which does not appear to be relevant.

We may decide that this is not important and that there is nothing to do for this ticket. It doesn't seem necessary to add an interstitial screen when the app is first run: most Android apps don't have that, and the license doesn't actually impose anything on the user.

**Comment by daira** [comment]
We decided that it is sufficient to have a link to the license text in the app description in the Play Store.

**Comment by true-jared** [comment]
So we should not add the Licensing text in this issue (https://github.com/Electric-Coin-Company/zashi/issues/23) in place of the custom EULA? How shall we reference it in the app description- are we gonna have an URL? @daira

**Comment by true-jared** [comment]
@daira Pinging you again regarding my questions above, please. 🙏🏽 I have already added the text as a custom EULA to the AppStore, and it passed review successfully. How shall we reference it in PlayStore? Please let me know.

**Comment by true-jared** [comment]
Chris mentioned that the language is already a part of Privacy Policy. @daira please let me know your thoughts on this.

**Comment by true-jared** [comment]
@daira Could you please let me know about this when you have a moment? We are planning to publicly release tomorrow if all goes well.

**Comment by daira** [comment]
Sorry I didn't notice the pings. If it is part of the Privacy Policy *and* the Privacy policy is linked from the app description, that's sufficient.

**Comment by true-jared** [comment]
Closing this issue then. 🫡
