### ISSUE TITLE
Check Android resource strings (in localization files) for correctness

### ISSUE THREAD

**Issue by str4d** [Electric-Coin-Company/zashi-android#1252]
Most of the current text comes from Figma, but some of it was to handle edge cases. All of it should be reviewed for correctness before 1.0.

**Comment by HonzaR** [comment]
Attaching zip with the current string resources used in UI. [zashi_ui_string_resources.zip](https://github.com/Electric-Coin-Company/zashi-android/files/15078135/zashi_ui_string_resources.zip) @true-jared
