### ISSUE TITLE
persist the user's server selection at all times and show a correct state of the button

### ISSUE THREAD

**Issue by true-jared** [Electric-Coin-Company/zashi-android#1287]
- this is an important follow-up task to this PR: https://github.com/Electric-Coin-Company/zashi-android/pull/1274

**Business Logic**
- when the custom server option is selected, it should always stay selected but at the moment that custom option changes unexpectedly to a predefined option (when a user leaves and re-enters the screen)
- we should NEVER change the selection of the user in this case because it may endanger their security

**UX:** 
- When save is pressed, we should disable the back button, so it's not possible to leave the screen while processing the request. The button should also be greyed out so it's obvious the back button is disabled.
- Figma design: https://www.figma.com/file/vYQD6uZtkPgtmgJ3zfauq0/Zashi-UI?type=design&node-id=4196-54667&mode=design&t=wrexWtvbgg1YvnH8-4

**Comment by HonzaR** [comment]
The UI and logic are properly implemented according to the design doc and feature requirements. The only missing part is presented in the attached video. You can see the edge case when user types exactly the same host and port as some of the endpoints from the list above. Then, after the Server screen is revisited, the stored endpoint matches the endpoint from the list. Do we need to handle it, or we say it’s expected?

https://github.com/Electric-Coin-Company/zashi-android/assets/9017390/4f1efb5e-3be8-4548-a19c-be5c884cfb7b

**Comment by true-jared** [comment]
Deprioritized as an edge case which does not impact user's selection.
