### ISSUE TITLE
Shielding transaction UI 

### ISSUE THREAD

**Issue by true-jared** [Electric-Coin-Company/zashi-android#1416]
- implement shielding transaction UI
- Final designs in Figma: https://www.figma.com/file/vYQD6uZtkPgtmgJ3zfauq0/Zashi-UI?type=design&node-id=2053-16416&mode=design&t=fu0piuvvDHEs4PmQ-4

<img width="735" alt="Screenshot 2024-05-01 at 13 41 58" src="https://github.com/Electric-Coin-Company/zashi-android/assets/109794238/5afd8c62-55b4-479e-ad61-b821bd66bf43">

- in the proposal we have a flag for shielding transactions but we need the information for Transaction History - that information should be in the V-transactions view (shielded notes received in a transaction and transparent notes getting spent)

**Comment by Milan-Cerovsky** [comment]
Postponing until FFI is done
