### ISSUE TITLE
[Bug] in Balances after unsuccessful Send 

### ISSUE THREAD

**Issue by true-jared** [Electric-Coin-Company/zashi-android#1423]
- i was trying to send some zec to a friend, first transaction failed and i received an error message, but later all my balances got wrong and shows much more zec than i hold
- After almost so much of time like hours, i got everything settled, my balances have come down to my real balance. This is a bad experience, i hope the problems will get solved once the POS is live, are you considering the SOL pos, proof of history?? Though it is very much filled with memes and hiccups, i felt they do it very fast.
My humble request is, even though everything is cypherpunk, speed is what we need in this time , for a normal user we think all about in movie download time, i can get 1 gb of movie in under 2 minutes, i love zcash i want to be a part of it . Please listen to the community
- I was not recovering my wallet but was sending zec to a friend who just got his zashi downloaded for the first time, this wallet i created just 5 months ago, Probably not sandblasted. Before i used to send zec from my ywallet to zashi, and it was very fast . Does it have something to do with the fee or amount. I was just moving . 05 the fee was around . 002

- reported on Discord: https://discord.com/channels/1133829162591846461/1133829407295942666/1234930522493554698

**Comment by true-jared** [comment]
@nuttycom I created a task for the issue reported on Discord, let us know if you have any findings since you said you are looking into it.

**Comment by HonzaR** [comment]
This issue waits on the Rust side of the SDK update.

**Comment by HonzaR** [comment]
Closing as resolved by previous Rust/SDK side updates.
