### ISSUE TITLE
[Bug] Shielding transaction error

### ISSUE THREAD

**Issue by true-jared** [Electric-Coin-Company/zashi-android#1424]
- a user has encountered an error when shielding funds, a transaction failed and they supposedly cannot see their funds reflected in Balances
- Slack thread with the report and debugging discussion: https://zcash.slack.com/archives/C06S4T7F3J5/p1714554857767659

**Comment by daira** [comment]
Shielding should never cause a reduction in overall balance; we should count the funds we are shielding as still being owned by the user's wallet.

**Comment by HonzaR** [comment]
As all the balances come from the SDK's Rust layer, we cannot handle balance changes from the Zashi side. This issue, as discussed internally, waits for the Rust layer update.

**Comment by HonzaR** [comment]
Closing as already resolved by some of the previous SDK and Zashi updates in the transparent funds shielding logic.
