### ISSUE TITLE
Add Correct Light Theme Colors for Wallet Details

### ISSUE THREAD

**Issue by ccjernigan** [Electric-Coin-Company/zashi-android#159]
As a followup to #62, the color values need to be added for the light theme on this screen.  Currently, the implementation re-uses the colors from the dark theme.

See Color.kt
```
    val addressHighlightBorder = Color(0xFF525252)
    val addressHighlightUnified = Color(0xFFFFD800)
    val addressHighlightOrchard = Color(0xFFFFD800)
    val addressHighlightSapling = Color(0xFF1BBFF6)
    val addressHighlightTransparent = Color(0xFF97999A)
    val addressHighlightViewing = Color(0xFF504062)
```

**Comment by ccjernigan** [comment]
@geffenz would you be able to help me verify the hex values in this file?  Once I know the correct values, then I can quickly update it.

https://github.com/zcash/secant-android-wallet/blob/main/ui-lib/src/main/java/cash/z/ecc/ui/theme/Color.kt

**Comment by HonzaR** [comment]
Closing as not needed anymore.
