### ISSUE TITLE
Ellipsize Center of UA Address in Profile Screen

### ISSUE THREAD

**Issue by ccjernigan** [Electric-Coin-Company/zashi-android#163]
As a followup to #145, the design calls for ellipsizing the UA address in the center while Compose only supports ellipsizing at the end of the string.

The solution will probably be to refactor the address abbreviation logic being implemented as part of the Zec send screen to something that can be used throughout the application.

**Comment by HonzaR** [comment]
Update: there is existing [issue](https://issuetracker.google.com/issues/185418980) in Google Issue Tracker related to more Ellipsize options in Jetpack Compose texts components. Or we could go with a custom solution like [this](https://stackoverflow.com/questions/69083061/how-to-make-middle-ellipsis-in-text-with-jetpack-compose/), if needed earlier.

**Comment by HonzaR** [comment]
Closing as not required by the latest design.
