### ISSUE TITLE
Support usage of spend authority controlled by a Keystone device

### ISSUE THREAD

**Issue by daira** [Electric-Coin-Company/zashi-android#1670]
This issue is complete once it is possible to install the Zashi app and set it up to use a Keystone device for all funds.

Support for having a Keystone device alongside a non-Keystone account is not tracked by this issue.

**Comment by HonzaR** [comment]
Removing #410 as a prerequisite to this for the upcoming release, as discussed internally.

**Comment by HonzaR** [comment]
Closing as done as part of #1661
