### ISSUE TITLE
build Zashi/Keystone wallet switch + flow for Connect Hardware Wallet

### ISSUE THREAD

**Issue by true-jared** [Electric-Coin-Company/zashi-android#1706]
_**BUILD ZASHI / KEYSTONE WALLET SWITCH:**_

- add [Zashi/Keystone wallet switch](https://www.figma.com/design/0E8ycv6g75rkrp268G2NMV/Keystone-Hardware-Wallet?node-id=349-2899&t=q7ubUfGiVnkImnZV-4) to the header and update the [Settings and Show/Hide](https://www.figma.com/design/0E8ycv6g75rkrp268G2NMV/Keystone-Hardware-Wallet?node-id=349-2907&t=q7ubUfGiVnkImnZV-4) icons globally
- upon tap on the switch, pop up a bottom sheet:
  - [by default](https://www.figma.com/design/0E8ycv6g75rkrp268G2NMV/Keystone-Hardware-Wallet?node-id=349-3467&t=q7ubUfGiVnkImnZV-4) display the Zashi wallet, a promo offer button (leading to a buy URL), and a [Connect Hardware Wallet] button
  - when a user taps on the [Connect Hardware Wallet] button, they will enter the flow for adding the hardware wallet (specified below) 
  - once a user has connected a Keystone Hardware Wallet, display the [Zashi and Keystone wallet buttons](https://www.figma.com/design/0E8ycv6g75rkrp268G2NMV/Keystone-Hardware-Wallet?node-id=427-1996&t=q7ubUfGiVnkImnZV-4), and allow the user to switch between the wallets
  - this global switch allows the user to:
    1. see their wallet balance and transactions in a separated view
    2. switch wallets to send transactions from
    3. view the wallet Balances and shield its funds
    4. see addresses of the wallet in the Receive tab

_**BUILD THE FLOW FOR CONNECTING HARDWARE WALLET:**_

1. a user taps on the button [Connect Hardware Wallet]
2. a user is navigated to the [Connect Hardware Wallet screen](https://www.figma.com/design/0E8ycv6g75rkrp268G2NMV/Keystone-Hardware-Wallet?node-id=349-3230&t=q7ubUfGiVnkImnZV-4)
  - display the explanation and steps to connect
  - allow the user to navigate to a tutorial by tapping on the View Keystone Tutorial link
3. when a user taps on the [Continue] button, open [Scan UI](https://www.figma.com/design/0E8ycv6g75rkrp268G2NMV/Keystone-Hardware-Wallet?node-id=349-3319&t=q7ubUfGiVnkImnZV-4) with instructions "Scan your Keystone wallet to connect" and the flashlight icon
  - if a user taps on the Cancel button, route them back to Connect Hardware Wallet screen
4. once a user scans a QR code displayed on their Keystone hardware wallet, they should be routed to [the next screen](https://www.figma.com/design/0E8ycv6g75rkrp268G2NMV/Keystone-Hardware-Wallet?node-id=349-3601&t=q7ubUfGiVnkImnZV-4) to confirm the wallet they wish to connect
  - the button Unlock is disabled until a user checks the checkbox
  - if a user taps on the button Forget this device, abort the flow, and route them back to the home screen
  - once a user taps on the button Unlock, they should be routed back to the home screen and have Keystone selected in the wallet switch

**Comment by HonzaR** [comment]
Closing as finished as part of #1707
