### ISSUE TITLE
as a user I can sign a transaction with the Keystone hardware wallet

### ISSUE THREAD

**Issue by true-jared** [Electric-Coin-Company/zashi-android#1710]
ZASHI / KEYSTONE SWITCH

- as a user I can switch between Zashi and Keystone wallet by tapping on [the Zashi/Keystone dropdown](https://www.figma.com/design/0E8ycv6g75rkrp268G2NMV/Keystone-Hardware-Wallet?node-id=349-6580&t=PIF9fCxkSPCKp0vb-4) and selecting the wallet [in the bottom sheet](https://www.figma.com/design/0E8ycv6g75rkrp268G2NMV/Keystone-Hardware-Wallet?node-id=349-6670&t=PIF9fCxkSPCKp0vb-4)
  - if a user has a Zashi wallet selected - the transaction should be sent from the Zashi wallet
  - if a user has a Keystone wallet selected - the transaction should be sent from the Keystone wallet

SEND A TRANSACTION FROM KEYSTONE ACCOUNT

1. if a user has a Keystone wallet connected, once they click on the Address Book icon in the [Send to] field, they should see [an updated version of Address Book screen](https://www.figma.com/design/0E8ycv6g75rkrp268G2NMV/Keystone-Hardware-Wallet?node-id=349-6419&t=PIF9fCxkSPCKp0vb-4) which also displays the addresses of their connected wallets at the top of the screen with the header "Your Wallets" 
  - implement [empty state](https://www.figma.com/design/0E8ycv6g75rkrp268G2NMV/Keystone-Hardware-Wallet?node-id=349-6353&t=PIF9fCxkSPCKp0vb-4) for the updated version of the Address Book screen 

2. update the Confirmation Screen:
  - change screen title to "REVIEW"
  - center the Total Amount (this change should be propagated to our regular Confirmation screen as well)
  - add "Send from" information with the[ Zashi logo](https://www.figma.com/design/0E8ycv6g75rkrp268G2NMV/Keystone-Hardware-Wallet?node-id=441-1816&t=PIF9fCxkSPCKp0vb-4) / [Keystone logo](https://www.figma.com/design/0E8ycv6g75rkrp268G2NMV/Keystone-Hardware-Wallet?node-id=349-6108&t=PIF9fCxkSPCKp0vb-4)
  - if a user taps on [Confirm with Keystone] button, we should generate the QR code they can scan with their Keystone device and route them to the new Sign Transaction screen (specified below) 
  - if a user taps on the [Cancel] button, route them back to the pre-filled Send screen

3. build the [new Sign Transaction screen](https://www.figma.com/design/0E8ycv6g75rkrp268G2NMV/Keystone-Hardware-Wallet?node-id=349-6220&t=PIF9fCxkSPCKp0vb-4)
  - display [the Keystone label](https://www.figma.com/design/0E8ycv6g75rkrp268G2NMV/Keystone-Hardware-Wallet?node-id=349-6248&t=PIF9fCxkSPCKp0vb-4) with the first 20 characters of the wallet address in the header together with a new [Hardware] label
  - display [the QR code with the encoded PCZT](https://www.figma.com/design/0E8ycv6g75rkrp268G2NMV/Keystone-Hardware-Wallet?node-id=349-6257&t=PIF9fCxkSPCKp0vb-4) for the user to scan with their Keystone device
  - display [instructions](https://www.figma.com/design/0E8ycv6g75rkrp268G2NMV/Keystone-Hardware-Wallet?node-id=349-6259&t=PIF9fCxkSPCKp0vb-4) for the user under the QR code
  - when a user taps on the [Reject] button, route them back to the Account screen and reset the Send form
  - when a user taps on the [Get Signature] button, route them to [the Scan screen with instructions](https://www.figma.com/design/0E8ycv6g75rkrp268G2NMV/Keystone-Hardware-Wallet?node-id=561-4648&t=PIF9fCxkSPCKp0vb-4)
    - once a user scans the signature QR code, route them to [the transaction progress screen](https://www.figma.com/design/0E8ycv6g75rkrp268G2NMV/Keystone-Hardware-Wallet?node-id=561-4715&t=PIF9fCxkSPCKp0vb-4)
    - if a user taps on the [Cancel] button on the Scan screen, route them back to the [Sign Transaction screen](https://www.figma.com/design/0E8ycv6g75rkrp268G2NMV/Keystone-Hardware-Wallet?node-id=349-6220&t=PIF9fCxkSPCKp0vb-4)

**Comment by HonzaR** [comment]
Closing as finished as part of #1707
