### ISSUE TITLE
Support deep linked requests

### ISSUE THREAD

**Issue by ccjernigan** [Electric-Coin-Company/zashi-android#202]
## Is your feature request related to a problem? Please describe.
As part of implementing zcash/secant-android-wallet#134, the app should able to handle deep link requests of the zcash URI scheme.

## Describe the solution you'd like
There are several parts to this implementation:
 - Android Manifest entries for the URI scheme
 - Handling in the Navigation component to support deep links
 - zcash/zcash-android-wallet-sdk#397 URI construction and parsing logic

**Comment by nuttycom** [comment]
Duplicate of #146
