### ISSUE TITLE
Add error handling UI for ZEC send UI

### ISSUE THREAD

**Issue by ccjernigan** [Electric-Coin-Company/zashi-android#250]
## Is your feature request related to a problem? Please describe.
This is similar to #215. 

The user can provide bad input to the ZEC send form

## Describe the solution you'd like
The send ZEC screen should provide good feedback to the user about errors on the form input.

 - Amount too small (cannot cover fee)
 - Amount too large (exceeds current balance)
 - Bad address

**Comment by daira** [comment]
This looks like a duplicate of #340.

**Comment by str4d** [comment]
Closing because we have started using #340 for this.
