### ISSUE TITLE
[Scaffold] Transaction Details

### ISSUE THREAD

**Issue by pacu** [Electric-Coin-Company/zashi-android#315]

**Comment by geffenz** [comment]
![image.png](https://images.zenhubusercontent.com/5ddc49a1bc69ec000196b9a0/7183a49a-6077-40c5-9eea-1252bc34481b)

**Comment by geffenz** [comment]
Raw Design files here : 
https://xd.adobe.com/view/404a8087-d246-45a5-b89f-701a964171ed-1519/

**Comment by geffenz** [comment]
While listing transactions is problematic, we could deeplink to the wallets last (or first!) or id of tx.
