### ISSUE TITLE
Contact Support Fails without Email Client

### ISSUE THREAD

**Issue by ccjernigan** [Electric-Coin-Company/zashi-android#386]
### Describe the issue
Contact Support will fail on a device without an email app.  For example, an Android TV device.

#### If so, please list the steps to reproduce below:
1. Install the app on a device without an app to handle email URIs
2. Visit the contact support screen
3. Fill in a message
4. Hit send

### Expected behavior
Since there's no app to handle email, one of three options:
 - Don't allow users to visit Contact Support at all
 - Display a SnackBar when sending fails, explaining that no email app could be found
 - Fall back to using a web service API request, which would require prompting the user for a reply-to email

### Actual behavior + errors
App silently fails

**Comment by HonzaR** [comment]
Closing as resolved by displaying an informative snackbar.
