### ISSUE TITLE
Research if we can disable 3rd party keyboards

### ISSUE THREAD

**Issue by geffenz** [Electric-Coin-Company/zashi-android#412]
To avoid privacy leaks and bad UX we may want to disable 3rd party keyboards. We can do this in iOS but need to research for Android.

**Comment by Milan-Cerovsky** [comment]
Unlike iOS, Android does not provide a way to disable 3rd party keyboards. This leaves us with 2 options.

1. Create or own keyboard
2. Notify a user with a security warning dialog when we detect he is using 3rd party keyboard

More info: https://maheshikapiumi.medium.com/allowance-of-third-party-keyboards-in-android-fbb3e6175378

**Comment by Milan-Cerovsky** [comment]
@true-jared we can close this one I guess
