### ISSUE TITLE
Design system

### ISSUE THREAD

**Issue by ccjernigan** [Electric-Coin-Company/zashi-android#611]
### Expectations
- Have a design language for ECC, but also match user expectations on a per-platform basis
- Push design to be a bit more rational instead of emotional (e.g. semantic styles shared across each screen rather than different font sizes everywhere based on “how they look”)
Go screen by screen and file issues to approximate our current screens UI to the designs (texts, paddings, sizes, shades, etc.)

### Strings
- Google Play translation service
- Probably make keys consistent with iOS and use Google Play translation service
- We’d write a small script to probably convert the XML to the iOS strings format (it will get us 99% of the way there and we might manually resolve any weird corner cases)

### Colors 
- Already designed by Geffen. We got a file with colors

### Paddings
- Prepare a separate Dimens class, which will hold needed spacing values, and also enables us to switch between these predefined group of spacing for small/normal/large screens as well as for portrait/landscape, etc.

### Additional notes
- Check all screens on a very small device to ensure we are all set up everywhere (scrolling, sizing, etc.)
- Adaptive layouts: https://developer.android.com/jetpack/compose/layouts/adaptive

**Comment by HonzaR** [comment]
Closing as all the subtasks were implemented.
