### ISSUE TITLE
Seed phrase completion is a bit janky

### ISSUE THREAD

**Issue by ccjernigan** [Electric-Coin-Company/zashi-android#675]
### Describe the issue
During restore of a wallet, the screen bounces because the views for autocomplete or errors are different heights, causing the screen to bounce a bit.

#### If so, please list the steps to reproduce below:
1. Restore an existing wallet
2. Manually type seed phrase words until the screen is filled and starts to scroll
3. Type something incorrect or start typing to hide/show the autocomplete suggestions

### Expected behavior
We should discuss with @geffenz 

### Actual behavior + errors
https://user-images.githubusercontent.com/699907/203544103-36c96f5b-6a06-484f-860f-eea9042cb993.mov

**Comment by HonzaR** [comment]
Closing this as improved by reworking into the new UI.
