### ISSUE TITLE
Add birthday to My secret phrase screen

### ISSUE THREAD

**Issue by ccjernigan** [Electric-Coin-Company/zashi-android#815]
## Is your feature request related to a problem? Please describe.
When users restore their wallets, it is helpful to have the birthday.

## Describe the solution you'd like
Show the birthday of the wallet.  Ideally, we should show the block height of the first transaction.

Note that the detected first transaction might be different from the birthday the user entered when setting up the wallet.  We should consider if/how to convey this to the user.

**Comment by HonzaR** [comment]
Closing as already implemented.
