### ISSUE TITLE
Core BTS UI Improvements

### ISSUE THREAD

**Issue by nuttycom** [Electric-Coin-Company/zashi-android#940]
The overall objective of this epic is to update the user interface elements of the Android implementation of the Zashi cryptocurrency wallet conform to the design described by 

https://www.figma.com/file/vYQD6uZtkPgtmgJ3zfauq0/Zashi-branding-ADJY-MOCK?type=design&node-id=0%3A1&mode=design&t=9FayedV7L5uAZNyV-1

**Comment by HonzaR** [comment]
Hello, welcome. Before anyone starts to work on these tasks, it's good to check our public documentation at:
- [Readme](https://github.com/zcash/secant-android-wallet/blob/main/README.md)
- Other important documentation like [Contributing](https://github.com/zcash/secant-android-wallet/blob/main/docs/CONTRIBUTING.md), [Setup](https://github.com/zcash/secant-android-wallet/blob/main/docs/Setup.md), and [Architecture](https://github.com/zcash/secant-android-wallet/blob/main/docs/Architecture.md)

Even though we are an open-source company and Android repositories are accessible publicly, we have a list of advice and undocumented things for a better understanding of our development process, which speeds up proper contribution. @nuttycom please, make sure that anyone who will participate on these tasks has access to the following:
- Undocumented things for Android
- Engineering Guide
